package com.infra.mapper.generate;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.name
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.comment
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.deletedFlg
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    private Integer deletedflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.version
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.name
     *
     * @return the value of userinfo.name
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.name
     *
     * @param name the value for userinfo.name
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.comment
     *
     * @return the value of userinfo.comment
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.comment
     *
     * @param comment the value for userinfo.comment
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.deletedFlg
     *
     * @return the value of userinfo.deletedFlg
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    public Integer getDeletedflg() {
        return deletedflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.deletedFlg
     *
     * @param deletedflg the value for userinfo.deletedFlg
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    public void setDeletedflg(Integer deletedflg) {
        this.deletedflg = deletedflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.version
     *
     * @return the value of userinfo.version
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.version
     *
     * @param version the value for userinfo.version
     *
     * @mbg.generated Mon Jul 02 03:34:50 JST 2018
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}